version: '3.8'

networks:
  my-network:

services:

  server-service:
    image: docker.jesusyaro.com/server
    build:
      context: ./server
      dockerfile: ./Dockerfile-dev
    container_name: server-container
    volumes:
      - ./server/:/usr/src/app
    ports:
      - '3000:3000'
    stdin_open: true
    networks:
      - my-network
    environment:
      - FRONTEND=localhost